name: Contribution snake

on:
  schedule:
    - cron: "17 7 * * *"
  workflow_dispatch:
  push:
    branches: [main]
    paths-ignore:
      - "dist/**"

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg?palette=github&color_snake=#216e39
            dist/github-snake-dark.svg?palette=github-dark&color_snake=#3fb950
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update contribution snake
          file_pattern: dist/*.svg
